### ISSUE TITLE
Slow mouse in EGLFS

### ISSUE THREAD

**Issue by schinkengott** [neuronalmotion/qtrpi#67]
hi guys,
is there any trick to get rid of the slow mouse in eglfs?
Even if i just start an empty qtwidget, the mouse is kinda "slow", it hangs a little bit.
its not "direct"
any tips?

**Comment by synapticvoid** [comment]
Hi @schinkengott ,

We did not encounter this issue. Do you have the same problem elsewhere on the Raspberry Pi ? 

I've stumbled upon this [post](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=84999), does it help ?

Anyway, I don't think this issue is specific to QtRPi, I may close the issue in a couple of days.

**Comment by synapticvoid** [comment]
Issue seems abandonned, closing the issue for now.
